# Generated by Django 3.2.8 on 2021-10-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=240)),
                ('company_name', models.CharField(max_length=240)),
                ('login_state', models.CharField(choices=[('a', 'asking'), ('y', 'yes'), ('n', 'no')], default='a', max_length=1)),
            ],
        ),
    ]
